# WARNING: auto-generated by Makefile release target -- run 'make release' to update

version = "0.12.0rc5"
git_commit = "980a8a0"  # the commit JUST BEFORE the release
version_date = "2024-04-17 17:16"  # UTC
