# WARNING: auto-generated by Makefile release target -- run 'make release' to update

version = "0.11.0rc8"
git_commit = "1d72438"  # the commit JUST BEFORE the release
version_date = "2024-02-27 14:07"  # UTC
