# WARNING: auto-generated by Makefile release target -- run 'make release' to update

version = "0.12.0"
git_commit = "95a3813"  # the commit JUST BEFORE the release
version_date = "2024-04-24 14:50"  # UTC
