name: publish
on:
  workflow_dispatch:
    inputs:
      release:
        description: 'The pycorelib release, e.g. v0.0.1-rc.1'
        required: true
        type: string
      environment:
        type: choice
        description: pypi environment
        options:
        - pypi-dev-rudder
        - pypi-test
        - pypi-prod
      
permissions:
  contents: read

jobs:
  profiles-pycorelib:
    name: publish profiles-pycorelib
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ inputs.release }}
      GH_TOKEN: ${{ secrets.PAT }}
      USER: ${{ secrets.USER }}
      PASSWORD: ${{ secrets.PASSWORD }}
    environment:
      name: ${{ inputs.environment }}
      url: ${{ vars.URL }}/profiles-pycorelib
    permissions:
      id-token: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - name: download
        shell: bash
        run: |
          gh release download ${VERSION} --repo github.com/rudderlabs/profiles-pycorelib --pattern "profiles_pycorelib_dist_${VERSION}.tar.gz" -O ./dist.tar.gz
          tar -zxvf dist.tar.gz
      - name: publish
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
        with:
          repository-url: ${{ vars.REPOSITORY_URL }}
          user: ${{ env.USER || '__token__' }}
          password: ${{ env.PASSWORD || '' }}
